#!/bin/bash
ask_yn() {
	while true; do
		response=""
		echo -n "y/n: $1 "
		read response

		if [ "$response" == "n" ] || [ "$response" == "y" ]; then
			break
		fi
	done
}
create() {
	if [ -n "$1" ]; then
		folders=""
		for i; do
			[ -d "$i" ] && folders="$i"$'\n'"$folders"
		done
	else
		folders="*/"
	fi
	echo "Found directories:"
	echo $folders | tr ' ' '\n' | sed 's/^/    /g'; echo
	ask_yn "Continue?"

	if [ "$response" == "y" ]; then
		pwd="$(pwd)"
		for i in $folders; do
			echo "Starting: $i"
			cd "$i"
			#align if there's more than one photo
			[ "$(ls *.* | wc -l)" -gt "1" ] && a="-a" || a=""
			flotografy $a $auto -ed 2 -d files *.*
			cd "$pwd"
			echo -e "\n\n\n"
		done
	else
		echo "Exiting..."
	fi
}
exif() {
	if [ -n "$1" ]; then
		folders=""
		for i; do
			[ -d "$i" ] && folders="$i"$'\n'"$folders"
		done
	else
		folders="$(find -name '*.png' | grep -e '\./.*/' | grep -v fattal | grep -v theexr | sed -r 's/\.\/(.*)\/.*$/\1/g' | sort -u)"
	fi
	echo "Found directories:"
	echo "$folders" | sed 's/^/     /g'
	ask_yn "Continue?"

	if [ "$response" == "y" ]; then
		IFS=$'\n'
		pwd="$(pwd)"
		for i in $folders; do
			cd "$i"
			flotografy -e $(ls | grep NEF | head -n 1) *.png
			cd "$pwd"
		done
	else
		echo "Exiting..."
	fi
}

auto=''
while [ -n "$1" ]; do
	case "$1" in
		"-c") shift; create $@;;
		"-e") shift; exif $@;;
		"-u") shift; auto="-u";;
		"-h") echo "Usage: flotografy_dirs [-u] [-c|-e [folders]]";;
	esac
	shift
done
