#!/bin/bash
ask_yn() {
	while true; do
		response=""
		echo -n "y/n: $1 "
		read response

		if [ "$response" == "n" ] || [ "$response" == "y" ]; then
			break
		fi
	done
}
create() {
	if [ -n "$1" ]; then
		folders=""
		for i; do
			[ -d "$i" ] && folders="$i"$'\n'"$folders"
		done
	else
		folders="*/"
	fi
	echo "Found directories:"
	echo $folders | tr ' ' '\n' | sed 's/^/    /g'; echo
	ask_yn "Continue?"

	if [ "$response" == "y" ]; then
		pwd="$(pwd)"
		for i in $folders; do
			echo "Starting: $i"
			cd "$i"
			unset a e
			num="$(ls *.* | wc -l)"
			#align if there's more than one photo
			[ "$num" -gt "1" ] && a="-a"
			#extend if there are three or less
			[ "$num" -le "3" ] && e="-ed 2"
			flotografy $o $e $a -d files *.*
			cd "$pwd"
			echo -e "\n\n\n"
		done
	else
		echo "Exiting..."
	fi
}
exif() {
	if [ -n "$1" ]; then
		folders=""
		for i; do
			[ -d "$i" ] && folders="$i"$'\n'"$folders"
		done
	else
		folders="$(find -name '*.png' | grep -e '\./.*/' | grep -v fattal | grep -v theexr | sed -r 's/\.\/(.*)\/.*$/\1/g' | sort -u)"
	fi
	echo "Found directories:"
	echo "$folders" | sed 's/^/     /g'
	ask_yn "Continue?"

	if [ "$response" == "y" ]; then
		IFS=$'\n'
		pwd="$(pwd)"
		for i in $folders; do
			cd "$i"
			flotografy -e $(ls | grep NEF | head -n 1) *.png -w $roundsize
			cd "$pwd"
		done
	else
		echo "Exiting..."
	fi
}

roundsize=412
while [ -n "$1" ]; do
	case "$1" in
		"-w") shift; roundsize="$1";;
		"-c") shift; create $@;;
		"-e") shift; exif $@;;
		"-u") auto="-u";;
		"-h") echo -e "Usage:\n\tflotografy_dirs [-u] -c [folders]\n\tflotografy_dirs [-w round width] -e [folders]";;
	esac
	shift
done
