#!/bin/bash
##
## Usage:
##   v2 [-a] *.tif
## 

aligned_prefix="aligned_"
enfuse_png="enfuse.png"
enfuse_exr="enfuse.exr"
fattal="fattal.png"
fattal_small="fattal_small.png"
cache="5120" #MB

f_align() {
	align_image_stack "$@" -m -c 8 -a "$aligned_prefix"
}

f_enfuse() {
	enfuse "$@" -m "$cache" -o "$enfuse_png"
}

f_fattal() {
	local half="${enfuse_exr//.exr/_half.exr}"
	local width=$(identify -format '%w' "$1")

	trap "echo \"Exiting...\"; rm \"$enfuse_exr\" \"$fattal_small\" \"$half\" &>/dev/null; exit 1" 2 15
	
	enfuse "$@" -m "$cache" -o "$enfuse_exr"
	convert -filter lanczos -resize "50%" "$enfuse_exr" "$half"

	pfsin "$half" | pfstmo_fattal02 -a 1 -b 0.9 -s 0.8 -n 0.010 | pfsoutppm -b 16 - | pnmtopng > "$fattal_small"
	convert -filter lanczos -depth 16 -resize "$width" "$fattal_small" "$fattal"

	rm "$enfuse_exr" "$fattal_small" "$half"
	trap - 2 15
}

if [[ $1 == "-a" ]]; then
	shift

	f_align "$@"
	f_enfuse "${aligned_prefix}"*.tif &
else
	f_enfuse "$@" &
fi

f_fattal "$@" &
wait
